export interface MenuItem {
  name: string;
  price: number;
}

export interface MenuCategory {
  id: string;
  title: string;
  emoji: string;
  items: MenuItem[];
}

export const menuData: MenuCategory[] = [
  {
    id: "soups",
    title: "Soups",
    emoji: "🍜",
    items: [
      { name: "Veg Manchow Soup", price: 70 },
      { name: "Veg Hot N Sour Soup", price: 70 },
      { name: "Lemon Coriander Soup", price: 90 },
      { name: "Noodles Soup", price: 90 },
      { name: "Malaysian Potato Soup", price: 90 },
      { name: "Cream of Tomato Soup", price: 90 },
      { name: "Cream of Mushroom Soup", price: 90 },
      { name: "Mushroom Soup", price: 90 },
      { name: "Nilkanth Spl Veg Soup", price: 100 },
    ],
  },
  {
    id: "salads",
    title: "Salads & Sides",
    emoji: "🥗",
    items: [
      { name: "Green Salad", price: 50 },
      { name: "Cucumber Salad", price: 50 },
      { name: "Onion Salad", price: 30 },
      { name: "Mix Raita", price: 50 },
      { name: "Masala Papad", price: 30 },
      { name: "Fry Papad", price: 20 },
      { name: "Roasted Masala Papad", price: 30 },
      { name: "Plain Roasted Papad", price: 20 },
    ],
  },
  {
    id: "starters",
    title: "Starters",
    emoji: "🍢",
    items: [
      { name: "Veg Lollipop", price: 150 },
      { name: "Mushroom Pakoda", price: 160 },
      { name: "Mushroom Chilli", price: 160 },
      { name: "Mushroom Chatpata", price: 160 },
      { name: "Mushroom 65", price: 160 },
      { name: "Garlic Mushroom", price: 160 },
      { name: "Hot Garlic Mushroom", price: 160 },
      { name: "Mushroom Salt & Pepper", price: 180 },
      { name: "Shanghai Mushroom", price: 180 },
      { name: "Thai Mushroom", price: 180 },
      { name: "Singaporean Mushroom", price: 180 },
      { name: "Sesame Mushroom", price: 160 },
      { name: "Mushroom Stick", price: 160 },
      { name: "Mushroom Manchurian", price: 160 },
      { name: "Paneer Chilli", price: 160 },
      { name: "Paneer Chatpata", price: 160 },
      { name: "Paneer 65", price: 160 },
      { name: "Garlic Paneer", price: 160 },
      { name: "Hot Garlic Paneer", price: 160 },
      { name: "Shanghai Paneer", price: 180 },
      { name: "Sesame Paneer", price: 180 },
      { name: "Thai Paneer", price: 180 },
      { name: "Paneer Stick", price: 160 },
      { name: "Paneer Manchurian", price: 160 },
      { name: "Paneer Salt & Pepper", price: 160 },
      { name: "Dragon Paneer", price: 180 },
      { name: "Paneer Kurkure", price: 160 },
      { name: "Devil Paneer", price: 180 },
      { name: "Paneer Popcorn", price: 160 },
      { name: "Paneer Fingers", price: 120 },
      { name: "Paneer Pakoda", price: 100 },
      { name: "Corn Salt & Pepper", price: 160 },
      { name: "Crispy Chilli Baby Corn", price: 160 },
      { name: "Baby Corn Manchurian", price: 120 },
      { name: "Honey Chilli Potato", price: 100 },
    ],
  },
  {
    id: "tandoori",
    title: "Tandoori",
    emoji: "🔥",
    items: [
      { name: "Paneer Tikka", price: 180 },
      { name: "Hariyali Paneer Tikka", price: 180 },
      { name: "Paneer Lasuni Kabab", price: 180 },
      { name: "Methi Paneer Tikka", price: 180 },
      { name: "Achari Paneer Tikka", price: 180 },
      { name: "Mushroom Tikka", price: 160 },
      { name: "Mushroom Lasuni Kabab", price: 160 },
      { name: "Veg Hara Bhara Kabab", price: 150 },
      { name: "Veg Shami Kabab", price: 150 },
      { name: "Tandoori Gobi", price: 100 },
      { name: "Tandoori Potato", price: 100 },
    ],
  },
  {
    id: "dal",
    title: "Dal",
    emoji: "🫕",
    items: [
      { name: "Dal Fry", price: 60 },
      { name: "Dal Tadka", price: 80 },
      { name: "Mix Dal", price: 80 },
      { name: "Dal Makhani", price: 80 },
      { name: "Veg Tadka", price: 80 },
      { name: "Punjabi Dal Tadka", price: 100 },
    ],
  },
  {
    id: "main-course",
    title: "Main Course",
    emoji: "🍛",
    items: [
      { name: "Veg Lazez", price: 150 },
      { name: "Paneer Lajawab", price: 150 },
      { name: "Veg Punjabi Masala", price: 150 },
      { name: "Veg Pesawari", price: 150 },
      { name: "Veg Bhuna Masala", price: 150 },
      { name: "Veg Dewani Handi", price: 150 },
      { name: "Veg Manpasand", price: 160 },
      { name: "Paneer Butter Masala", price: 180 },
      { name: "Paneer Tikka Masala", price: 160 },
      { name: "Paneer Masala", price: 160 },
      { name: "Paneer Lababdar", price: 160 },
      { name: "Paneer Korma", price: 160 },
      { name: "Palak Paneer", price: 160 },
      { name: "Paneer Kaleji", price: 160 },
      { name: "Paneer Pasanda", price: 160 },
      { name: "Paneer Maharaja", price: 180 },
      { name: "Paneer Methi Chaman", price: 180 },
      { name: "Matar Paneer", price: 160 },
      { name: "Mushroom Butter Masala", price: 180 },
      { name: "Mushroom Masala", price: 160 },
      { name: "Mushroom Kadai", price: 160 },
      { name: "Mushroom Handi", price: 160 },
      { name: "Mushroom Kolhapuri", price: 160 },
      { name: "Mushroom Hyderabadi", price: 160 },
      { name: "Matar Mushroom", price: 160 },
      { name: "Mushroom Punjabi Masala", price: 160 },
      { name: "Mushroom Lababdar", price: 160 },
      { name: "Paneer Kadai", price: 160 },
      { name: "Paneer Handi", price: 160 },
      { name: "Paneer Kolhapuri", price: 160 },
      { name: "Paneer Hyderabadi", price: 160 },
      { name: "Kaju Curry", price: 150 },
      { name: "Kaju Masala", price: 150 },
      { name: "Kaju Tomato Masala", price: 150 },
      { name: "Khoya Kaju", price: 150 },
      { name: "Kaju Paneer Masala", price: 160 },
      { name: "Malai Kofta", price: 160 },
      { name: "Bahubali Kofta Curry", price: 160 },
      { name: "Paneer Kofta Curry", price: 160 },
      { name: "Kofta E Lazez", price: 160 },
      { name: "Nargisi Kofta Curry", price: 160 },
      { name: "Lasooni Kofta Curry", price: 160 },
      { name: "Veg Kadai", price: 120 },
      { name: "Mix Veg Curry", price: 100 },
      { name: "Veg Handi", price: 120 },
      { name: "Veg Kolhapuri", price: 150 },
      { name: "Veg Makhani", price: 150 },
    ],
  },
  {
    id: "rice",
    title: "Rice",
    emoji: "🍚",
    items: [
      { name: "Plain Rice", price: 60 },
      { name: "Curd Rice", price: 80 },
      { name: "Lemon Rice", price: 80 },
      { name: "Jeera Rice", price: 120 },
      { name: "Ghee Rice", price: 120 },
      { name: "Kaju Ghee Rice", price: 150 },
      { name: "Tomato Rice", price: 120 },
      { name: "Basmati Chawal Ka Mazaa", price: 180 },
    ],
  },
  {
    id: "biryani",
    title: "Biryani",
    emoji: "🥘",
    items: [
      { name: "Veg Pulao", price: 150 },
      { name: "Kashmiri Pulao", price: 180 },
      { name: "Veg Biryani", price: 160 },
      { name: "Spl Veg Biryani", price: 180 },
      { name: "Paneer Biryani", price: 180 },
      { name: "Mushroom Biryani", price: 180 },
    ],
  },
  {
    id: "noodles",
    title: "Noodles",
    emoji: "🍝",
    items: [
      { name: "Veg Noodles", price: 100 },
      { name: "Mix Veg Noodles", price: 130 },
      { name: "Paneer Noodles", price: 130 },
      { name: "Mushroom Noodles", price: 130 },
      { name: "Chilli Garlic Veg Noodles", price: 130 },
      { name: "Shanghai Noodles", price: 130 },
      { name: "Sesame Garlic Noodles", price: 130 },
      { name: "Singaporean Noodles", price: 130 },
      { name: "Schezwan Noodles", price: 130 },
      { name: "Triple Noodles", price: 150 },
    ],
  },
  {
    id: "fried-rice",
    title: "Fried Rice",
    emoji: "🍳",
    items: [
      { name: "Veg Fried Rice", price: 120 },
      { name: "Mix Veg Fried Rice", price: 150 },
      { name: "Paneer Fried Rice", price: 150 },
      { name: "Mushroom Fried Rice", price: 150 },
      { name: "Chilli Garlic Fried Rice", price: 150 },
      { name: "Shanghai Fried Rice", price: 150 },
      { name: "Sesame Garlic Fried Rice", price: 150 },
      { name: "Singaporean Fried Rice", price: 150 },
      { name: "Schezwan Fried Rice", price: 150 },
    ],
  },
  {
    id: "naan-roti",
    title: "Naan & Roti",
    emoji: "🫓",
    items: [
      { name: "Roti", price: 4 },
      { name: "Butter Naan", price: 30 },
      { name: "Garlic Naan", price: 50 },
      { name: "Masala Naan", price: 50 },
      { name: "Mint Naan", price: 30 },
      { name: "Methi Paratha", price: 50 },
      { name: "Butter Kulcha (Plain)", price: 30 },
      { name: "Masala Kulcha", price: 50 },
      { name: "Paneer Kulcha", price: 50 },
    ],
  },
  {
    id: "desserts",
    title: "Desserts",
    emoji: "🍮",
    items: [
      { name: "Veg Custard", price: 50 },
      { name: "Rabdi", price: 50 },
      { name: "Rasmalai", price: 50 },
    ],
  },
  {
    id: "cold-drinks",
    title: "Cold Drinks",
    emoji: "🥤",
    items: [
      { name: "Plain Cold Drink", price: 30 },
      { name: "Masala Cold Drink", price: 50 },
      { name: "Masala Soda", price: 50 },
    ],
  },
];

// Placeholder image URLs using food category-based SVG placeholders
export const categoryImages: Record<string, string> = {
  soups: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop",
  salads: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop",
  starters: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&h=300&fit=crop",
  tandoori: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&h=300&fit=crop",
  dal: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400&h=300&fit=crop",
  "main-course": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop",
  rice: "https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=400&h=300&fit=crop",
  biryani: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop",
  noodles: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=400&h=300&fit=crop",
  "fried-rice": "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=400&h=300&fit=crop",
  "naan-roti": "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&h=300&fit=crop",
  desserts: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=400&h=300&fit=crop",
  "cold-drinks": "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&h=300&fit=crop",
};
